source 'https://rubygems.org'
gem 'sinatra', '2.1.0'
gem 'thin', '1.8.1'
gem 'puma', '5.5.0'
gem 'reel', '0.6.1'
gem 'http', '5.0.4'
gem 'webrick', '1.7.0'
gem 'json'
gem 'mysql2'
gem 'uuid'
gem 'logger'
